### ISSUE TITLE
Fix loading screen

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/poa-faucet#13]
![image](https://user-images.githubusercontent.com/9360827/44816681-d2cf1c00-ab97-11e8-8b40-18fd48180203.png)

@vbaranov

**Comment by vbaranov** [comment]
@rstormsf I guess, the issue is with your browser cache. CSS updates were made to hide Illuminati logo. Please, clear cache in your browser to fix it.

**Comment by vbaranov** [comment]
I will close that. Please, reopen it, if clearing the cache didn't help.
