### ISSUE TITLE
(Bug) Loader has incorrect text

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/poa-faucet#14]
<img width="1440" alt="screen shot 2018-09-07 at 6 13 32 am" src="https://user-images.githubusercontent.com/14067096/45220924-b6507500-b264-11e8-94ac-b64cc62e2f84.png">

**Comment by vbaranov** [comment]
@dennis00010011b please clear the cache of your browser and reopen the page. Does it help? See https://github.com/poanetwork/poa-faucet/issues/13#issuecomment-418289125

**Comment by dennis00010011b** [comment]
It didn't help
I've tried two browsers:
1. Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)
2.Firefox v 61.0.2 Build ID 20180807170231

MacOs, HighSierra 10.13.6

**Comment by vbaranov** [comment]
@dennis00010011b thanks for the debug. The issue was with Retina display. Fixed now. Could you check once more?

**Comment by dennis00010011b** [comment]
@vbaranov 
issue fixed
Checked with latest Chrome and Firefox for devices:
 1. MacBook Pro, Retina 15.4-inch (2880 x 1800) , High Sierra 10.13.6
 2. Dell  Inspiron-3558, Ubuntu 16
